config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :sucursales
  resources :empleados
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'usuarios#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/checkEmail', to: 'usuarios#checkEmail'
  get '/checkRFC', to: 'usuarios#checkRFC'
  get '/checkNombreSucursal', to: 'sucursales#checkNombreSucursal'

  get 'home/index'
  get 'admin', to: 'home#admin'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@sucursales = Sucursal.where(usuario: current_user)
  end

  def admin
  	@usuarios = Usuario.all
  	@sucursales = Sucursal.all
  	@empleados = Empleado.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <h1 class="title">Admin</h1>
  </div>
</section>

<section class="section">
	<div class="tabs is-centered">
	  <ul>
	    <li class="is-active" data-tab="usuarios"><a>Usuarios</a></li>
	    <li data-tab="sucursales"><a>Sucursales</a></li>
	    <li data-tab="empleados"><a>Empleados</a></li>
	  </ul>
	</div>	
</section>

<section class="section" id="tab-content">
	<div class="table-container" id="usuarios">
    <table class="table is-bordered is-striped is-fullwidth is-hoverable">
      <thead>
        <tr>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Email</th>
          <th>Rfc</th>
          <th>Empresa</th>
          <th>ID</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.nombres %></td>
          <td><%= usuario.apellidos %></td>
          <td><%= usuario.email %></td>
          <td><%= usuario.RFC %></td>
          <td><%= usuario.empresa %></td>
          <td><%= usuario.id %></td>
          <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
          <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: 'Desea eliminar este usuario?' }, class: 'has-text-danger'%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  	</div>

  	<div class="table-container is-hidden" id="sucursales">
    <table class="table is-bordered is-striped is-fullwidth is-hoverable">
      <thead>
        <tr>
      		<th>Nombre</th>
      		<th>Calle</th>
      		<th>Colonia</th>
      		<th>Numero exterior</th>
      		<th>Numero interior</th>
      		<th>Codigo postal</th>
      		<th>Ciudad</th>
      		<th>Pais</th>
      		<th>Usuario</th>
      		<th>ID</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @sucursales.each do |sucursal| %>
        <tr>
        	<td><%= sucursal.nombre %></td>
        	<td><%= sucursal.calle %></td>
        	<td><%= sucursal.colonia %></td>
        	<td><%= sucursal.numero_exterior %></td>
        	<td><%= sucursal.numero_interior %></td>
        	<td><%= sucursal.codigo_postal %></td>
        	<td><%= sucursal.ciudad %></td>
        	<td><%= sucursal.pais %></td>
        	<td><%= sucursal.usuario_id %></td>
        	<td><%= sucursal.id %></td>
        	<td><%= link_to 'Edit', edit_sucursal_path(sucursal) %></td>
        	<td><%= link_to 'Destroy', sucursal, method: :delete, data: { confirm: 'esea eliminar esta sucursal?' } %>
        </tr>
        <% end %>
      </tbody>
    </table>
  	</div>

	<div class="table-container is-hidden" id="empleados">
    <table class="table is-bordered is-striped is-fullwidth is-hoverable">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Apellidos</th>
          <th>RFC</th>
          <th>Puesto</th>
          <th>Sucursal</th>
          <th>ID</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @empleados.each do |empleado| %>
        <tr>
          <td><%= empleado.nombres %></td>
          <td><%= empleado.apellidos %></td>
          <td><%= empleado.RFC %></td>
          <td><%= empleado.puesto %></td>
          <td><%= empleado.sucursal.nombre %></td>
          <td><%= empleado.id %></td>
          <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
          <td><%= link_to 'Eliminar', empleado, method: :delete, data: { confirm: 'Desea eliminar este empleado?' }, class: 'has-text-danger'%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  	</div>
</section>

<script type="text/javascript">
	var tabs = $('.tabs li');
	tabs.on('click', function() {
		var tab = $(this).data('tab');

		tabs.removeClass('is-active');
		$(this).addClass('is-active');

		$('#tab-content div').addClass('is-hidden');
		$('#'+tab).removeClass('is-hidden');
	})
</script>

app/views/home/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        Bienvenido <%= current_user.nombres %>!
      </h1>
      
      <% if (notice) %>
        <div class="notification is-success is-light">
          <p class="has-text-centered"><%= notice %></p> 
        </div>     
      <% end %>

      <% if @sucursales.count > 0 %>
      <h1 class="subtitle">Tus Sucursales</h1>
      <div class="table-container">
        <table class="table is-bordered is-striped is-fullwidth is-hoverable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Empleados</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @sucursales.each do |sucursal| %>
            <tr>
              <td><%= sucursal.nombre %></td>
              <td><%= sucursal.empleados.count %></td>
              <td><%= link_to 'Editar', edit_sucursal_path(sucursal) %></td>
              <td><%= link_to 'Eliminar', sucursal, method: :delete, data: { confirm: 'Desea eliminar esta sucursal?' }, class: 'has-text-danger' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <% else %>       

      <div class="columns">
        <div class="column is-one-third is-offset-one-third">
          <article class="message is-warning">
            <div class="message-body">
              <h1 class="title is-5">Aun no has registrado sucursales!</h1>
            </div>
          </article>
        </div>          
      </div>

      <% end %>

      <br>
      <%= link_to 'Registrar Sucursal', new_sucursal_path, {class: 'button is-info'} %>
      <%= link_to 'Registrar Empleado', new_empleado_path, {class: 'button is-info'} %>

    </div>
  </div>
 
</section>