config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :sucursales
  resources :empleados
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'usuarios#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/checkEmail', to: 'usuarios#checkEmail'
  get '/checkRFC', to: 'usuarios#checkRFC'
  get '/checkNombreSucursal', to: 'sucursales#checkNombreSucursal'

  get 'home/index'
  get 'admin', to: 'home#admin'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :sucursal
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
    @sucursales = Sucursal.where(usuario: current_user)
  end

  # GET /empleados/1/edit
  def edit
    @sucursales = Sucursal.where(usuario: current_user)
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        #format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.html { 
          flash[:notice] = 'Empleado creado!' 
          redirect_to edit_sucursal_path(@empleado.sucursal_id)
        }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        #format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.html { 
          flash[:notice] = 'Empleado actualizado!' 
          redirect_to edit_sucursal_path(@empleado.sucursal_id)
        }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      #format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.html { 
          flash[:notice] = 'Empleado eliminado!' 
          redirect_to edit_sucursal_path(@empleado.sucursal_id)
        }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empleado_params
      params.require(:empleado).permit(:nombres, :apellidos, :RFC, :puesto, :sucursal_id)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_with model: @empleado, local: true, id: 'crear-sucursal-form' do |form| %>

<div class="columns">
  <div class="column">
    <div class="field">
      <%= form.label :Nombres, 'Nombres', class:  'label' %>
      <div class="control">
        <%= form.text_field :nombres, class: 'input' %>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="field">
      <%= form.label :apellidos, 'Apellidos', class:  'label' %>
      <div class="control">
        <%= form.text_field :apellidos, class: 'input' %>
      </div>
    </div>
  </div>
</div>

<div class="field">
  <%= form.label :RFC, 'RFC', class:  'label' %>
  <div class="control">
    <%= form.text_field :RFC, class: 'input' %>
  </div>
</div>
<div class="columns">
  <div class="column">
    <div class="field">
      <%= form.label :puesto, 'Puesto', class: 'label' %>
      <div class="control">
        <%= form.text_field :puesto, class: 'input' %>
      </div>
    </div>  
  </div>

  <div class="column">
    <div class="field">
      <%= form.label :sucursal, 'Sucursal', class:  'label' %>
      <div class="select is-fullwidth">
        <% sucursales_valores = @sucursales.map { |sucursal| [sucursal.nombre, sucursal.id]} %>
        <%= form.select :sucursal_id, sucursales_valores, include_blank: 'Seleccionar sucursal' %>
      </div>
    </div>
  </div>
</div>

<div class="field has-text-centered">
  <div class="control">
    <%= link_to 'Cancelar', home_index_path, {class: 'button is-warning'} %>
    <%= form.submit 'Guardar', class: 'button is-primary' %>
  </div>
</div>
<% end %>

app/views/empleados/edit.html.erb
<section class="hero is-info">
	<div class="hero-body">
		<h1 class="title">Crear Empleado</h1>
	</div>
</section>

<section class="section">
	<%= form_with model: @empleado, local: true, id: 'crear-sucursal-form' do |form| %>

		<div class="columns">
			<div class="column">
				<div class="field">
					<%= form.label :Nombres, 'Nombres', class:  'label' %>
					<div class="control">
						<%= form.text_field :nombres, class: 'input' %>
					</div>
				</div>
			</div>
			<div class="column">
				<div class="field">
					<%= form.label :apellidos, 'Apellidos', class:  'label' %>
					<div class="control">
						<%= form.text_field :apellidos, class: 'input' %>
					</div>
				</div>
			</div>
		</div>

		<div class="columns">
			<div class="column">
				<div class="field">
					<%= form.label :puesto, 'Puesto', class: 'label' %>
					<div class="control">
						<%= form.text_field :puesto, class: 'input' %>
					</div>
				</div>	
			</div>

			<div class="column">
				<div class="field">
					<%= form.label :sucursal, 'Sucursal', class:  'label' %>
					<div class="select is-fullwidth">
						<% sucursales_valores = @sucursales.map { |sucursal| [sucursal.nombre, sucursal.id]} %>
						<%= form.select :sucursal_id, options_for_select(sucursales_valores) %>
					</div>
				</div>
			</div>
		</div>

		<div class="field has-text-centered">
            <div class="control">
            	<%= link_to 'Cancelar', home_index_path, {class: 'button is-warning'} %>
                <%= form.submit 'Guardar', class: 'button is-primary' %>
            </div>
        </div>
	<% end %>
</section>

<%= javascript_pack_tag 'empleado_validation' %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Rfc</th>
      <th>Puesto</th>
      <th>Sucursal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombres %></td>
        <td><%= empleado.apellidos %></td>
        <td><%= empleado.RFC %></td>
        <td><%= empleado.puesto %></td>
        <td><%= empleado.sucursal_id %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<section class="hero is-info">
	<div class="hero-body">
		<h1 class="title">Crear Empleado</h1>
	</div>
</section>

<section class="section">
	<%= render 'form', empleado: @empleado %>
</section>

<%= javascript_pack_tag 'empleado_validation' %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @empleado.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @empleado.apellidos %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @empleado.RFC %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @empleado.puesto %>
</p>

<p>
  <strong>Sucursal:</strong>
  <%= @empleado.sucursal_id %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>