config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :sucursales
  resources :empleados
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'usuarios#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/checkEmail', to: 'usuarios#checkEmail'
  get '/checkRFC', to: 'usuarios#checkRFC'
  get '/checkNombreSucursal', to: 'sucursales#checkNombreSucursal'

  get 'home/index'
  get 'admin', to: 'home#admin'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  has_many :sucursales, dependent: :destroy

  #validates_uniqueness_of :email
  #validates_uniqueness_of :RFC
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    if logged_in?
      redirect_to :controller => 'home'
    end
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        #format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.html { 
          flash[:notice] = 'Cuenta creada!' 
          redirect_to root_url         
        }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkEmail
    @email = params[:usuario]['email'] # Saca email del objeto mandado
    @usuario = Usuario.find_by email: @email
    respond_to do |format|
      # Si usuario es blank regresa true
      format.json { render :json => @usuario.blank? }
    end
  end

  def checkRFC
    @RFC = params[params.keys()[0]]['RFC'] # Saca RFC del objeto mandado
    @usuario = Usuario.find_by RFC: @RFC
    @empleado = Empleado.find_by RFC: @RFC
    respond_to do |format|
      # Regresa si usuario o empleado existe
      # Si usuario Y empleado son nil regresa true
      format.json { render :json => @usuario.blank? && @empleado.blank? }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombres, :apellidos, :email, :RFC, :empresa, :password, :password_confirmation)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with model: usuario, local: true, id: 'register-form' do |form| %>
<% if usuario.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:
  </h2>           

  <ul>
    <% usuario.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="columns">
  <div class="column field py-0">
    <%= form.label :nombres, 'Nombres', class:  'label' %>
    <div class="control">
      <%= form.text_field :nombres, class: 'input' %>
    </div>
  </div>

  <div class="column field py-0">
    <%= form.label :apellidos, 'Apellidos', class: 'label' %>
    <div class="control">
      <%= form.text_field :apellidos, class: 'input' %>
    </div>
  </div>
</div>

<div class="columns">     
  <div class="column field py-0">
    <%= form.label :email, 'Correo', class: 'label' %>
    <div class="control">
      <%= form.text_field :email, class: 'input' %>
    </div>
  </div>

  <div class="column field py-0">
    <%= form.label :empresa, 'Empresa', class: 'label' %>
    <div class="control">
      <%= form.text_field :empresa, class: 'input' %>
      <p class="help is-danger"></p>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column field">
    <%= form.label :RFC, 'RFC', class: 'label' %>
    <div class="control is-expanded">
      <%= form.text_field :RFC, class: 'input is-fullwidth' %>
    </div>
  </div>          
</div>

<div class="columns">         
  <div class="column field py-0">
    <%= form.label :password, 'Contraseña', class: 'label' %>
    <div class="control">
      <%= form.password_field :password, class: 'input' %>
    </div>
  </div>

  <div class="column field py-0">
    <%= form.label :password_confirmation, 'Confirmar contraseña', class: ' label' %> 
    <div class="control"> 
      <%= form.password_field :password_confirmation, class: 'input' %>
    </div>  
  </div>
</div>

<div class="field has-text-centered">
  <div class="control">
    <%= form.submit 'Crear', class: 'button is-primary' %>
  </div>
</div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Rfc</th>
      <th>Empresa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombres %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.RFC %></td>
        <td><%= usuario.empresa %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<section class="section">
  <div class="columns">
    <div class="column is-half is-offset-one-quarter">      

        <div class="card-content" id="register-card-content">
          <h1 class="title">Bienvenido!</h1>
          <p class="subtitle is-size-6">Llena el formulario para crear tu cuenta.</p>
          <%= render 'form', usuario: @usuario %>
          <p class="has-text-danger" id="register-errors"></p>
        </div>
        
        <footer class="card-footer">
	        <%= link_to 'Acceder', login_path, {class: 'button is-info is-fullwidth'} %> 
        </footer>
      </div>
    </div>
  </div>  
</section>

<%= javascript_pack_tag 'signup_validation' %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @usuario.RFC %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @usuario.empresa %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>