config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :sucursales
  resources :empleados
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'usuarios#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/checkEmail', to: 'usuarios#checkEmail'
  get '/checkRFC', to: 'usuarios#checkRFC'
  get '/checkNombreSucursal', to: 'sucursales#checkNombreSucursal'

  get 'home/index'
  get 'admin', to: 'home#admin'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/sucursales_controller.rb
class SucursalesController < ApplicationController
  before_action :set_sucursal, only: [:show, :edit, :update, :destroy]

  # GET /sucursales
  # GET /sucursales.json
  def index
    @sucursales = Sucursal.all
  end

  # GET /sucursales/1
  # GET /sucursales/1.json
  def show
  end

  # GET /sucursales/new
  def new
    @sucursal = Sucursal.new
  end

  # GET /sucursales/1/edit
  def edit
    @empleados = Empleado.where(sucursal: params[:id])
  end

  # POST /sucursales
  # POST /sucursales.json
  def create
    @sucursal = Sucursal.new(sucursal_params)
    @sucursal.usuario = current_user

    respond_to do |format|
      if @sucursal.save
        #format.html { redirect_to @sucursal, notice: 'Sucursal was successfully created.' }
        format.html { 
          flash[:notice] = 'Sucursal creada!' 
          redirect_to :controller => 'home'          
        }
        format.json { render :show, status: :created, location: @sucursal }
      else
        format.html { render :new }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sucursales/1
  # PATCH/PUT /sucursales/1.json
  def update
    respond_to do |format|
      if @sucursal.update(sucursal_params)
        #format.html { redirect_to @sucursal, notice: 'Sucursal was successfully updated.' }
        format.html { 
          flash[:notice] = 'Sucursal editada!' 
          redirect_to :controller => 'home'          
        }
        format.json { render :show, status: :ok, location: @sucursal }
      else
        format.html { render :edit }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursales/1
  # DELETE /sucursales/1.json
  def destroy
    @sucursal.destroy
    respond_to do |format|
      #format.html { redirect_to sucursales_url, notice: 'Sucursal was successfully destroyed.' }
      format.html { 
          flash[:notice] = 'Sucursal eliminada!' 
          redirect_to :controller => 'home'          
        }
      format.json { head :no_content }
    end
  end

  def checkNombreSucursal
    @nombre = params[:sucursal][:nombre]
    @sucursal = Sucursal.where(nombre: @nombre, usuario: current_user) 
    respond_to do |format|
      # Regresa si usuario o empleado existe
      # Si usuario Y empleado son nil regresa true
      format.json { render :json => @sucursal.blank? }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sucursal_params
      params.require(:sucursal).permit(:nombre, :calle, :colonia, :numero_exterior, :numero_interior, :codigo_postal, :ciudad, :pais, :usuario_id)
    end
end

app/helpers/sucursales_helper.rb
module SucursalesHelper
end

app/views/sucursales/_form.html.erb
<%= form_with model: @sucursal, local: true, id: 'crear-sucursal-form' do |form| %>
<div class="columns">
  <div class="column field">
    <%= form.label :nombres, 'Nombre', class:  'label' %>
    <div class="control">
      <%= form.text_field :nombre, class: 'input' %>
    </div>
  </div>
  <div class="column field">
    <%= form.label :calle, 'Calle', class:  'label' %>
    <div class="control">
      <%= form.text_field :calle, class: 'input' %>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column field">
    <%= form.label :colonia, 'Colonia', class:  'label' %>
    <div class="control">
      <%= form.text_field :colonia, class: 'input' %>
    </div>
  </div>
  <div class="column field">
    <%= form.label :numero_exterior, 'Numero Exterior', class:  'label' %>
    <div class="control">
      <%= form.text_field :numero_exterior, class: 'input' %>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column field">
    <%= form.label :numero_interior, 'Numero Interor', class:  'label' %>
    <div class="control">
      <%= form.text_field :numero_interior, class: 'input' %>
    </div>
  </div>
  <div class="column field">
    <%= form.label :codigo_postal, 'Codigo Postal', class:  'label' %>
    <div class="control">
      <%= form.text_field :codigo_postal, class: 'input' %>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column field">
    <%= form.label :ciudad, 'Ciudad', class:  'label' %>
    <div class="control">
      <%= form.text_field :ciudad, class: 'input' %>
    </div>
  </div>
  <div class="column field">
    <%= form.label :pais, 'Pais', class:  'label' %>
    <div class="control">
      <%= form.text_field :pais, class: 'input' %>
    </div>
  </div>
</div>

<div class="field has-text-centered">
  <div class="control">
    <%= link_to 'Cancelar', home_index_path, {class: 'button is-warning'} %>
    <%= form.submit 'Guardar', class: 'button is-primary' %>
  </div>
</div>
<% end %>

app/views/sucursales/edit.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <h1 class="title">Editar Sucursal</h1>
  </div>
</section>
<div class="tabs is-centered">
  <ul>
    <li class="is-active" onclick="toggleTabs()" id="mostrar-detalles"><a>Detalles</a></li>
    <li onclick="toggleTabs()" id="mostrar-empleados"><a>Empleados</a></li>
  </ul>
</div>

<% if (notice) %>
  <div class="notification is-success is-light">
    <p class="has-text-centered"><%= notice %></p>          
  </div>     
<% end %>

<section class="section" id="detalles-seccion">
  <%= render 'form', sucursal: @sucursal %>
</section>

<section class="section is-hidden" id="empleados-seccion">
  <% if @empleados.count > 0 %>
  <div class="table-container">
    <table class="table is-bordered is-striped is-fullwidth is-hoverable">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Apellidos</th>
          <th>RFC</th>
          <th>Puesto</th>
          <th>Sucursal</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @empleados.each do |empleado| %>
        <tr>
          <td><%= empleado.nombres %></td>
          <td><%= empleado.apellidos %></td>
          <td><%= empleado.RFC %></td>
          <td><%= empleado.puesto %></td>
          <td><%= empleado.sucursal.nombre %></td>
          <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
          <td><%= link_to 'Eliminar', empleado, method: :delete, data: { confirm: 'Desea eliminar este empleado?' }, class: 'has-text-danger'%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <% else %>       

  <div class="columns">
    <div class="column is-one-third is-offset-one-third">
      <article class="message is-warning">
        <div class="message-body">
          <h1 class="title is-5">Aun no has registrado empleados!</h1>
        </div>
      </article>
    </div>          
  </div>

  <% end %>

  <div class="container has-text-centered">
    <%= link_to 'Registrar Empleado', new_empleado_path, {class: 'button is-info'} %>
  </div>
</section>

<script type="text/javascript">
  function toggleTabs() {
    $('#detalles-seccion').toggleClass('is-hidden');
    $('#empleados-seccion').toggleClass('is-hidden');
    $('#mostrar-detalles').toggleClass('is-active');
    $('#mostrar-empleados').toggleClass('is-active');
  }
</script>
<%= javascript_pack_tag 'sucursal_validation' %>

app/views/sucursales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sucursales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Calle</th>
      <th>Colonia</th>
      <th>Numero exterior</th>
      <th>Numero interior</th>
      <th>Codigo postal</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sucursales.each do |sucursal| %>
      <tr>
        <td><%= sucursal.nombre %></td>
        <td><%= sucursal.calle %></td>
        <td><%= sucursal.colonia %></td>
        <td><%= sucursal.numero_exterior %></td>
        <td><%= sucursal.numero_interior %></td>
        <td><%= sucursal.codigo_postal %></td>
        <td><%= sucursal.ciudad %></td>
        <td><%= sucursal.pais %></td>
        <td><%= sucursal.usuario_id %></td>
        <td><%= link_to 'Show', sucursal %></td>
        <td><%= link_to 'Edit', edit_sucursal_path(sucursal) %></td>
        <td><%= link_to 'Destroy', sucursal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sucursal', new_sucursal_path %>

app/views/sucursales/new.html.erb
<section class="hero is-info">
	<div class="hero-body">
		<h1 class="title">Crear Sucursal</h1>
	</div>
</section>

<section class="section">
	<%= render 'form', sucursal: @sucursal %>
</section>

<%= javascript_pack_tag 'sucursal_validation' %>

app/views/sucursales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sucursal.nombre %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @sucursal.calle %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @sucursal.colonia %>
</p>

<p>
  <strong>Numero exterior:</strong>
  <%= @sucursal.numero_exterior %>
</p>

<p>
  <strong>Numero interior:</strong>
  <%= @sucursal.numero_interior %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @sucursal.codigo_postal %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @sucursal.ciudad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @sucursal.pais %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @sucursal.usuario_id %>
</p>

<%= link_to 'Edit', edit_sucursal_path(@sucursal) %> |
<%= link_to 'Back', sucursales_path %>